#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

ENV_FILE="${ENV_FILE:-.env}"

say() {
  printf '\n==> %s\n' "$1"
}

prompt() {
  local label="$1"
  local default="${2:-}"
  local value

  if [ -n "$default" ]; then
    read -r -p "${label} [${default}]: " value
    printf '%s' "${value:-$default}"
  else
    read -r -p "${label}: " value
    printf '%s' "$value"
  fi
}

prompt_secret() {
  local label="$1"
  local value

  read -r -s -p "${label}: " value
  printf '\n' >&2
  printf '%s' "$value"
}

confirm() {
  local label="$1"
  local default="${2:-n}"
  local value
  local hint="[y/N]"

  if [ "$default" = "y" ]; then
    hint="[Y/n]"
  fi

  read -r -p "${label} ${hint}: " value
  value="${value:-$default}"
  case "$value" in
    y|Y|yes|YES) return 0 ;;
    *) return 1 ;;
  esac
}

escape_env_value() {
  local value="$1"

  if [[ "$value" == *[[:space:]]* || "$value" == *#* || "$value" == *\"* || "$value" == *\$* || "$value" == *"'"* ]]; then
    value="${value//\\/\\\\}"
    value="${value//\"/\\\"}"
    value="${value//\$/\\$}"
    printf '"%s"' "$value"
  else
    printf '%s' "$value"
  fi
}

write_env_line() {
  local key="$1"
  local value="$2"

  printf '%s=%s\n' "$key" "$(escape_env_value "$value")" >> "$ENV_FILE.tmp"
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

mysql_base_args() {
  local host="$1"
  local user="$2"

  MYSQL_ARGS=(-h "$host" -u "$user")
}

run_mysql_file() {
  local file="$1"
  local db_name="${2:-}"

  mysql_base_args "$REALESTATE_DB_HOST" "$REALESTATE_DB_USER"
  if [ -n "$db_name" ]; then
    MYSQL_ARGS+=("$db_name")
  fi

  if [ -n "$REALESTATE_DB_PASS" ]; then
    MYSQL_PWD="$REALESTATE_DB_PASS" mysql "${MYSQL_ARGS[@]}" < "$file"
  else
    mysql "${MYSQL_ARGS[@]}" < "$file"
  fi
}

say "Checking required CLI tools"
missing=0
for tool in php mysql mysqldump git; do
  if command_exists "$tool"; then
    printf '  ok: %s\n' "$tool"
  else
    printf '  missing: %s\n' "$tool"
    missing=1
  fi
done

if [ "$missing" -ne 0 ]; then
  printf '\nInstall missing tools first, then rerun this script.\n' >&2
  exit 1
fi

if [ -f "$ENV_FILE" ]; then
  if confirm "$ENV_FILE already exists. Create backup and overwrite?" "n"; then
    cp "$ENV_FILE" "${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
  else
    printf 'Aborted without changing %s\n' "$ENV_FILE"
    exit 0
  fi
fi

say "Base application settings"
APP_URL="$(prompt "APP_URL" "http://elsesserandco-site.local")"
APP_ENV="$(prompt "APP_ENV" "development")"

say "Database settings"
REALESTATE_DB_HOST="$(prompt "REALESTATE_DB_HOST" "localhost")"
REALESTATE_DB_NAME="$(prompt "REALESTATE_DB_NAME" "realestate_db")"
REALESTATE_DB_USER="$(prompt "REALESTATE_DB_USER" "root")"
REALESTATE_DB_PASS="$(prompt_secret "REALESTATE_DB_PASS (leave empty for no password)")"
REALESTATE_DB_CHARSET="$(prompt "REALESTATE_DB_CHARSET" "utf8mb4")"

say "Mail settings"
MAIL_TRANSPORT="$(prompt "MAIL_TRANSPORT (smtp | mail | log)" "log")"
MAIL_HOST=""
MAIL_PORT=""
MAIL_USERNAME=""
MAIL_PASSWORD=""
MAIL_ENCRYPTION=""
MAIL_FROM_ADDRESS="$(prompt "MAIL_FROM_ADDRESS" "noreply@elsesserandco.com")"
MAIL_FROM_NAME="$(prompt "MAIL_FROM_NAME" "Elsesser & Co.")"

if [ "$MAIL_TRANSPORT" = "smtp" ]; then
  MAIL_HOST="$(prompt "MAIL_HOST" "smtp.yandex.ru")"
  MAIL_PORT="$(prompt "MAIL_PORT" "465")"
  MAIL_USERNAME="$(prompt "MAIL_USERNAME" "$MAIL_FROM_ADDRESS")"
  MAIL_PASSWORD="$(prompt_secret "MAIL_PASSWORD")"
  MAIL_ENCRYPTION="$(prompt "MAIL_ENCRYPTION (ssl | tls | empty)" "ssl")"
fi

say "Optional OAuth and integration keys"
VK_CLIENT_ID="$(prompt "VK_CLIENT_ID" "")"
VK_CLIENT_SECRET=""
if [ -n "$VK_CLIENT_ID" ]; then
  VK_CLIENT_SECRET="$(prompt_secret "VK_CLIENT_SECRET")"
fi

YANDEX_CLIENT_ID="$(prompt "YANDEX_CLIENT_ID" "")"
YANDEX_CLIENT_SECRET=""
if [ -n "$YANDEX_CLIENT_ID" ]; then
  YANDEX_CLIENT_SECRET="$(prompt_secret "YANDEX_CLIENT_SECRET")"
fi

GOOGLE_CLIENT_ID="$(prompt "GOOGLE_CLIENT_ID" "")"
GOOGLE_CLIENT_SECRET=""
if [ -n "$GOOGLE_CLIENT_ID" ]; then
  GOOGLE_CLIENT_SECRET="$(prompt_secret "GOOGLE_CLIENT_SECRET")"
fi

TELEGRAM_BOT_TOKEN="$(prompt_secret "TELEGRAM_BOT_TOKEN (optional)")"
TELEGRAM_BOT_USERNAME=""
if [ -n "$TELEGRAM_BOT_TOKEN" ]; then
  TELEGRAM_BOT_USERNAME="$(prompt "TELEGRAM_BOT_USERNAME" "")"
fi

VAPID_PUBLIC_KEY="$(prompt "VAPID_PUBLIC_KEY" "")"
VAPID_PRIVATE_KEY=""
if [ -n "$VAPID_PUBLIC_KEY" ]; then
  VAPID_PRIVATE_KEY="$(prompt_secret "VAPID_PRIVATE_KEY")"
fi
VAPID_SUBJECT="$(prompt "VAPID_SUBJECT" "mailto:admin@elsesserandco.com")"
YANDEX_MAPS_API_KEY="$(prompt "YANDEX_MAPS_API_KEY" "")"

say "Writing $ENV_FILE"
: > "$ENV_FILE.tmp"
{
  printf '# Generated by scripts/setup.sh on %s\n' "$(date -Iseconds)"
  printf '# Do not commit this file.\n\n'
} >> "$ENV_FILE.tmp"

write_env_line APP_URL "$APP_URL"
write_env_line APP_ENV "$APP_ENV"
printf '\n' >> "$ENV_FILE.tmp"

write_env_line REALESTATE_DB_HOST "$REALESTATE_DB_HOST"
write_env_line REALESTATE_DB_NAME "$REALESTATE_DB_NAME"
write_env_line REALESTATE_DB_USER "$REALESTATE_DB_USER"
write_env_line REALESTATE_DB_PASS "$REALESTATE_DB_PASS"
write_env_line REALESTATE_DB_CHARSET "$REALESTATE_DB_CHARSET"
printf '\n' >> "$ENV_FILE.tmp"

write_env_line MAIL_TRANSPORT "$MAIL_TRANSPORT"
write_env_line MAIL_HOST "$MAIL_HOST"
write_env_line MAIL_PORT "$MAIL_PORT"
write_env_line MAIL_USERNAME "$MAIL_USERNAME"
write_env_line MAIL_PASSWORD "$MAIL_PASSWORD"
write_env_line MAIL_ENCRYPTION "$MAIL_ENCRYPTION"
write_env_line MAIL_FROM_ADDRESS "$MAIL_FROM_ADDRESS"
write_env_line MAIL_FROM_NAME "$MAIL_FROM_NAME"
printf '\n' >> "$ENV_FILE.tmp"

write_env_line VK_CLIENT_ID "$VK_CLIENT_ID"
write_env_line VK_CLIENT_SECRET "$VK_CLIENT_SECRET"
write_env_line VK_REDIRECT_URI "${APP_URL}/oauth/vk/callback.php"
write_env_line YANDEX_CLIENT_ID "$YANDEX_CLIENT_ID"
write_env_line YANDEX_CLIENT_SECRET "$YANDEX_CLIENT_SECRET"
write_env_line YANDEX_REDIRECT_URI "${APP_URL}/oauth/yandex/callback.php"
write_env_line GOOGLE_CLIENT_ID "$GOOGLE_CLIENT_ID"
write_env_line GOOGLE_CLIENT_SECRET "$GOOGLE_CLIENT_SECRET"
write_env_line GOOGLE_REDIRECT_URI "${APP_URL}/oauth/google/callback.php"
printf '\n' >> "$ENV_FILE.tmp"

write_env_line TELEGRAM_BOT_TOKEN "$TELEGRAM_BOT_TOKEN"
write_env_line TELEGRAM_BOT_USERNAME "$TELEGRAM_BOT_USERNAME"
printf '\n' >> "$ENV_FILE.tmp"

write_env_line VAPID_PUBLIC_KEY "$VAPID_PUBLIC_KEY"
write_env_line VAPID_PRIVATE_KEY "$VAPID_PRIVATE_KEY"
write_env_line VAPID_SUBJECT "$VAPID_SUBJECT"
printf '\n' >> "$ENV_FILE.tmp"

write_env_line YANDEX_MAPS_API_KEY "$YANDEX_MAPS_API_KEY"

mv "$ENV_FILE.tmp" "$ENV_FILE"
chmod 600 "$ENV_FILE" 2>/dev/null || true

say "Preparing writable directories"
for dir in logs cache session uploads images/uploads; do
  mkdir -p "$dir"
  chmod 775 "$dir" 2>/dev/null || true
  printf '  ok: %s\n' "$dir"
done

if [ -f database/create_database.sql ] && confirm "Import database/create_database.sql now? Use only for a fresh/local database." "n"; then
  say "Importing base database schema"
  run_mysql_file database/create_database.sql
fi

if confirm "Run database migrations now?" "y"; then
  say "Running migrations"
  php database/migrate.php
fi

say "Setup complete"
printf 'Next checks:\n'
printf '  php database/migrate.php --status\n'
printf '  open %s in your browser\n' "$APP_URL"
